export const WINDOW_FRAME_CONTROLS_WIDTH = 138
export const FEEDBACK_BUTTON_WIDTH = 32
export const WINDOW_TITLEBAR_RIGHT_GAP = 4
export const WINDOW_TITLEBAR_RIGHT_RESERVED_WIDTH =
  WINDOW_FRAME_CONTROLS_WIDTH + FEEDBACK_BUTTON_WIDTH + WINDOW_TITLEBAR_RIGHT_GAP
